---
- name: Creates a new Virtual Machines from templates
  ovirt_vm:
    state: present
    name: "{{ item.name }}"
    template: "{{ item.template }}"
    cluster: "{{ item.cluster }}"
    nics: "{{ item.nics }}"
    clone: True
  loop: "{{ virtual_machines }}"
